'use strict';
// Application navigation and integration surfaces. Business handlers are connected module by module.
const OrdelyWorkspace = (() => {
  const operational = ['owner', 'admin', 'operator', 'finance'];
  const modules = [
    {route:'shipments',name:'Expediții',group:'OPERARE',icon:'parcel',context:'Shipping',modules:'10–12',description:'AWB-uri, etichete și expedieri legate de comenzile tale.',states:['De pregătit','AWB generat','Predată curierului','Livrată','Anulată'],columns:['Comandă','Curier','AWB','Ramburs','Stare'],steps:['Alege comanda','Pregătește coletul','Generează AWB','Predă curierului'],fields:['Comandă','Curier și serviciu','Colete / greutate','Adresă din comandă','Ramburs'],action:'Generează AWB',links:['commerce','tracking','invoicing'],note:'Sameday și FAN Courier vor fi conectate la același flux de expediere.',roles:operational},
    {route:'tracking',name:'Tracking',group:'OPERARE',icon:'route',context:'Shipping',modules:'12, 16',description:'Urmărește livrările și transporturile de retur.',states:['În tranzit','Livrată','Problemă de livrare','Refuzată','Retur în curs'],columns:['Comandă','AWB','Ultimul eveniment','Actualizat','Stare'],steps:['AWB existent','Evenimente curier','Stare normalizată','Acțiune operator'],fields:['AWB','Curier','Interval de actualizare'],action:'Actualizează tracking',links:['shipments','refusals','returns'],note:'Evenimentele curierului vor fi păstrate separat de confirmarea recepției fizice.',roles:operational},
    {route:'returns',name:'Retururi',group:'POST-VÂNZARE',icon:'return',context:'Returns',modules:'13, 16',description:'Solicitări, aprobare, transport și recepție retur.',states:['Solicitat','Aprobat','De ridicat','În transport','Recepționat','Inspectat','Închis','Respins'],columns:['Caz retur','Comandă','Produse / cantități','Rezoluție','Stare'],steps:['Solicitare','Aprobare','Transport inbound','Recepție și inspecție','Rezoluție'],fields:['Comandă originală','Produse și cantități','Motiv','Rambursare sau schimb'],action:'Înregistrează retur',links:['commerce','exchanges','refunds','portal'],note:'Returul obișnuit nu declanșează storno automat. Recepția nu reintegrează produse în stoc.',roles:operational},
    {route:'refusals',name:'Refuzuri de primire',group:'POST-VÂNZARE',icon:'return',context:'Returns',modules:'16, 09',description:'Refuzuri de livrare și documentele originale asociate.',states:['De verificat','Original verificat','Storno în așteptare','Storno confirmat','Necesită reconciliere'],columns:['Comandă','AWB','Factură originală','Refuz înregistrat','Storno'],steps:['Identifică refuzul','Verifică factura originală','Înregistrează refuzul','Storno automat','Reconciliere'],fields:['Comandă originală','AWB refuzat','Factura originală','Motivul refuzului'],action:'Înregistrează refuzul',links:['tracking','invoicing','returns'],note:'Storno automat numai la înregistrarea refuzului, pe original verificat; repetarea nu va dubla documentul.',roles:operational},
    {route:'exchanges',name:'Schimburi',group:'POST-VÂNZARE',icon:'exchange',context:'Exchanges',modules:'18–19',description:'Înlocuitorul, diferența manuală și expedierea schimbului.',states:['De selectat înlocuitor','Așteaptă returul','De pregătit','Expediat','Închis'],columns:['Schimb','Comandă originală','Înlocuitor','Diferență / transport','Stare'],steps:['Retur asociat','Alege înlocuitorul','Diferență manuală','Transport opțional','Expediere'],fields:['Retur asociat','Produs / variantă din CMS','Cantitate','Diferență de preț introdusă manual','Transport la tariful site-ului'],action:'Pregătește schimbul',links:['returns','shipments','invoicing'],note:'Diferența se introduce manual. Transportul selectat se adaugă la ramburs și se facturează pe datele inițiale.',roles:operational},
    {route:'resends',name:'Retrimiteri',group:'POST-VÂNZARE',icon:'parcel',context:'Exchanges',modules:'19',description:'O nouă expediere legată de comanda și coletul inițial.',states:['De pregătit','Pregătită','Expediată','Livrată','Anulată'],columns:['Retrimitere','Comandă','Expediere inițială','Ramburs','Stare'],steps:['Comandă originală','Motiv retrimitere','Selecție facturare','Colet nou'],fields:['Comandă originală','Expediere inițială','Motiv','Produse / transport de facturat'],action:'Pregătește retrimiterea',links:['commerce','shipments','invoicing'],note:'Nimic sau total zero la retrimitere înseamnă fără factură nouă și ramburs zero.',roles:operational},
    {route:'refunds',name:'Rambursări',group:'FINANCIAR',icon:'wallet',context:'Refunds',modules:'17',description:'Sumele de restituit, pregătirea plății și confirmarea ei.',states:['În așteptarea inspecției','De pregătit','Pregătită','De confirmat','Confirmată','Anulată'],columns:['Rambursare','Comandă / retur','Sumă','Destinație mascată','Stare'],steps:['Retur inspectat','Sumă eligibilă','Destinație verificată','Plată','Confirmare'],fields:['Retur inspectat','Sumă de restituit','Destinație de plată','Dovada și data confirmării'],action:'Pregătește rambursarea',links:['returns','invoicing'],note:'Storno nu confirmă plata. Datele bancare vor fi criptate și afișate numai persoanelor autorizate.',roles:['owner','admin','finance']},
    {route:'portal',name:'Portal clienți',group:'CONFIGURARE',icon:'portal',context:'Portal',modules:'14–15',description:'Un singur portal de retur și schimb, conectat la magazinele tale.',states:[],columns:[],steps:['Branding magazin','Identificare client','Produse eligibile','Solicitare retur / schimb','Urmărire caz'],fields:['Titlu și texte','Logo / culori','Politică de retur','Launcher Shopify și link alternativ'],action:'Publică portalul',links:['returns','exchanges','stores'],note:'Acesta este ecranul de administrare. Portalul public și sesiunea limitată la comandă urmează să fie conectate.',roles:['owner','admin'],allStores:true},
    {route:'settings',name:'Setări operaționale',group:'CONFIGURARE',icon:'settings',context:'Workspace',modules:'20',description:'Regulile de lucru și configurările pentru fiecare magazin.',states:[],columns:[],steps:['Magazin','Politici','Servicii asociate','Activare fluxuri'],fields:['Politică retur','Tarif transport din CMS','Serviciu curier implicit','Branding și acces portal'],action:'Salvează configurarea',links:['stores','integrations','portal'],note:'Gestiunea stocului, rezervările și reintegrarea rămân amânate pentru o zonă separată.',roles:['owner','admin'],allStores:true}
  ];
  const node = (tag, text, className) => {const element=document.createElement(tag); if(text!==undefined)element.textContent=text; if(className)element.className=className; return element;};
  function link(route, label, className='button-link secondary') {const element=node('a',label,className); element.href=`#${route}`; element.dataset.route=route; return element;}
  function icon(name) {const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('icon');svg.setAttribute('aria-hidden','true');const use=document.createElementNS(svg.namespaceURI,'use');use.setAttribute('href',`#icon-${name}`);svg.append(use);return svg;}
  const names={commerce:'Comenzi și catalog',invoicing:'Facturare',integrations:'Integrări',stores:'Magazine',...Object.fromEntries(modules.map(module=>[module.route,module.name]))};
  const pages=Object.fromEntries(modules.map(module=>[module.route,{name:module.name,title:module.name,description:module.description,eyebrow:module.group,roles:module.roles,allStores:module.allStores}]));
  const root=document.getElementById('workspace-pages');
  const nav=document.querySelector('.sidebar nav');
  const configuration=nav.querySelector('[data-route="stores"]').previousElementSibling;
  let group='';
  for(const module of modules) {
    if(module.group!==group){group=module.group;if(group!=='CONFIGURARE')nav.insertBefore(node('p',group,'nav-label'),configuration);}
    const navLink=link(module.route,module.name,'nav-item');navLink.prepend(icon(module.icon));
    if(group==='CONFIGURARE')nav.append(navLink);else nav.insertBefore(navLink,configuration);
    const section=node('section');section.dataset.page=module.route;section.setAttribute('aria-label',module.name);section.hidden=true;
    const notice=node('div',undefined,'notice');notice.append(node('strong','Structură pregătită'),node('p','Acest flux va deveni activ după conectarea funcțiilor sale.'));section.append(notice);
    const toolbar=node('div',undefined,'panel toolbar');const storeLabel=node('label','Magazin');const store=node('select');store.dataset.workspaceStore=module.route;storeLabel.append(store);toolbar.append(storeLabel);
    if(module.states.length){const label=node('label','Stare');const select=node('select');select.append(new Option('Toate stările',''));module.states.forEach(state=>select.append(new Option(state,state)));label.append(select);toolbar.append(label);}
    const actions=node('fieldset');actions.disabled=true;const action=node('button',module.action);action.type='button';actions.append(action);toolbar.append(actions);section.append(toolbar);
    const flow=node('ol',undefined,'workspace-flow');module.steps.forEach(step=>flow.append(node('li',step)));section.append(flow);
    if(module.columns.length){const container=node('div',undefined,'panel workspace-register');const table=node('table');table.append(node('caption',module.name));const head=node('thead'),row=node('tr');module.columns.forEach(column=>{const th=node('th',column);th.scope='col';row.append(th);});head.append(row);table.append(head);const body=node('tbody'),empty=node('tr'),cell=node('td','Lista va fi disponibilă când acest flux este activat.');cell.colSpan=module.columns.length;empty.append(cell);body.append(empty);table.append(body);container.append(table);section.append(container);}
    const lower=node('div',undefined,'workspace-columns');const form=node('section',undefined,'panel');form.append(node('h2',module.action));const fieldset=node('fieldset');fieldset.disabled=true;fieldset.append(node('legend','Date necesare'));const fields=node('div',undefined,'form-grid');module.fields.forEach(field=>{const label=node('label',field);const input=node('input');input.placeholder='Se va completa în acest flux';input.type='text';label.append(input);fields.append(label);});fieldset.append(fields);form.append(fieldset);form.append(node('p','Introducerea și salvarea acestor date vor fi activate odată cu fluxul.','hint'));lower.append(form);
    const related=node('section',undefined,'panel');related.append(node('h2','Legături în aplicație'),node('p',module.note));const links=node('div',undefined,'button-row');module.links.forEach(route=>links.append(link(route,names[route])));related.append(links);lower.append(related);section.append(lower);root.append(section);
    store.addEventListener('change',()=>{section.querySelectorAll('input').forEach(input=>input.value='');section.querySelectorAll('select:not([data-workspace-store])').forEach(select=>select.selectedIndex=0);});
  }
  const overview=document.getElementById('workspace-map');overview.append(node('h2','Fluxurile aplicației'),node('p','Comenzi și facturare sunt conectate la datele locale. Celelalte zone au structura pregătită.','hint'));
  const cards=node('div',undefined,'workspace-map');
  for(const module of modules){const card=link(module.route,'','workspace-module');card.append(icon(module.icon),node('strong',module.name),node('span','Structură pregătită','integration-badge'),node('small',module.description));cards.append(card);}overview.append(cards);
  document.addEventListener('ordely:context',event=>{const {stores}=event.detail;for(const section of root.children){const select=section.querySelector('[data-workspace-store]');select.replaceChildren(...stores.map(store=>new Option(store.name,store.id)));if(!stores.length)select.append(new Option('Niciun magazin disponibil',''));section.querySelectorAll('input').forEach(input=>input.value='');section.querySelectorAll('select:not([data-workspace-store])').forEach(filter=>filter.selectedIndex=0);}});
  document.addEventListener('ordely:logout',()=>{root.querySelectorAll('input').forEach(input=>input.value='');root.querySelectorAll('[data-workspace-store]').forEach(select=>select.replaceChildren());root.querySelectorAll('select:not([data-workspace-store])').forEach(filter=>filter.selectedIndex=0);});
  return Object.freeze({pages,modules:Object.freeze(modules)});
})();
